name: Build & Push
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      # 1) Login BEFORE setting up buildx so pulling BuildKit from GHCR is authenticated
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2) Use container driver; BuildKit image hosted on GHCR
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Build & push (frontend)
        uses: docker/build-push-action@v6
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/anqa-digital-health/anqa-platform-frontend:main
            ghcr.io/anqa-digital-health/anqa-platform-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Build & push (backend)
        uses: docker/build-push-action@v6
        with:
          context: ./apps/backend
          file: ./apps/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/anqa-digital-health/anqa-platform-backend:main
            ghcr.io/anqa-digital-health/anqa-platform-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
